KUNB2B-117 Create a profile user role use case
kununu/roles pull request #10
Opened 2020-10-15 10:41 UTC by davidribeiro-kununu

- Added dependencies of jms/serializer-bundle, kununu/cqrs-bundle, kununu/doctrine-dbal, kununu/rest-api-bundle, league/tactician-bundle, league/tactician-doctrine and ramsey/uuid
- Create migration to populate roles tables with admin, claimer and owner roles
- Removed roles:test command
- Created POST /user-roles endpoint
- Added AssignRoleToUser command use case
- Added GetRoleByUserAndResource query use case

2020-10-15 14:32 UTC, jcostaventureoak requested changes

2020-10-15 14:32 UTC, jcostaventureoak commented on services/src/UseCase/Query/GetRoleByUserAndResource/Query.php
> +    public function __construct(string $userUuid, string $roleName, string $resourceType, ?string $resourceUuid)
If the query its called `GetRoleByUserAndResource` why do we need the `$roleName` as a parameter?

2020-10-15 14:32 UTC, jcostaventureoak commented on services/src/Controller/UserRoles/UserRoleController.php
> +        return $this->queryBus->handle(new Query($userUuid, $roleName, $resourceType, $resourceUuid));
Shouldn't we avoid this extra query to get the user_roles and a read model directly from the handler?

2020-10-15 14:32 UTC, jcostaventureoak commented on services/src/UseCase/Query/GetRoleByUserAndResource/ReadModel/UserRole.php
> +        $this->userUuid = $userUuid;
I think you forget the the `id` field. We decide to pass it in the [response](https://jira.xing.hh/browse/KUNB2B-117?focusedCommentId=1619238&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1619238)

2020-10-15 15:14 UTC, davidribeiro-kununu commented on services/src/Domain/Role/Role.php
> +    public const KEY_OWNER = 'owner';
Sure, I'll change this

2020-10-15 15:17 UTC, davidribeiro-kununu commented on services/src/UseCase/Command/AssignRoleToUser/ProfileRoleCreator.php
> +        return (bool) $this->repository->userHasRoleForResource($author, $resourceType);
I've talked with Tamara to clarify this, and for a first iteration any user who has access to a profile can assign a role for other user. In short, claimers can create owners and vice-versa

2020-10-15 15:17 UTC, davidribeiro-kununu commented on services/src/Controller/UserRoles/UserRoleController.php
> +        return $this->queryBus->handle(new Query($userUuid, $roleName, $resourceType, $resourceUuid));
We can't cause we're using CQRS, so a Command use case doesn't return anything. If we need to retrieve the data, then we have to do a query after.
Eg: https://github.com/kununu/profiles/blob/master/services/src/Controller/Profiles/RefreshProfileByUuidController.php

2020-10-15 15:17 UTC, davidribeiro-kununu commented on services/src/UseCase/Query/GetRoleByUserAndResource/ReadModel/UserRole.php
> +        $this->userUuid = $userUuid;
Sure, I'll add it

2020-10-15 15:18 UTC, davidribeiro-kununu commented on services/src/UseCase/Query/GetRoleByUserAndResource/Query.php
> +    public function __construct(string $userUuid, string $roleName, string $resourceType, ?string $resourceUuid)
you're right, i'll change it

2020-10-16 08:55 UTC, jcostaventureoak commented on services/src/Controller/UserRoles/UserRoleController.php
> +        return $this->queryBus->handle(new Query($userUuid, $roleName, $resourceType, $resourceUuid));
Ok, thanks!

2020-10-21 08:42 UTC, jcostaventureoak approved these changes
LGTM

2020-10-22 09:41 UTC, merged