Kunb2b 104 create roles dev database
kununu/roles pull request #9
Opened 2020-10-09 10:00 UTC by davidribeiro-kununu

2020-10-09 12:58 UTC, tiagopinheiro-kununu reviewed
Please check the comments

2020-10-09 12:58 UTC, tiagopinheiro-kununu commented on services/src/Domain/Resource/ResourceType.php
> +    private const TYPES = ['admin', 'profile'];
admin and profiles could be constants so we can use them in the future?

2020-10-09 12:58 UTC, tiagopinheiro-kununu commented on services/composer.json
> +        "doctrine/orm": "^2.7",
Can you add on the project kununu/scripts package? 
Why? this has the code standards for PHP
After you can run composer kununu:cs-fixer-code src/* for all PHP files

        
 {
            "type": "vcs",
            "url": "https://github.com/kununu/kununu-scripts.git",
            "no-api": true
        },
      "require-dev": {
        "kununu/scripts": "*"
      },

2020-10-09 12:58 UTC, tiagopinheiro-kununu commented on services/src/Infrastructure/Persistence/Doctrine/Type/ActionType.php
> +        return ['created', 'accepted', 'rejected', 'deleted'];
constants can be created here 'created', 'accepted', 'rejected', 'deleted' so the values can be reused?

2020-10-09 12:58 UTC, tiagopinheiro-kununu commented on services/src/Infrastructure/Persistence/Doctrine/Migrations/Version20201008163730.php
> +    role_id INT UNSIGNED NOT NULL,
You are missing FK on role_id no?

2020-10-09 12:58 UTC, tiagopinheiro-kununu commented on services/src/Infrastructure/Persistence/Doctrine/Migrations/Version20201008163730.php
> +    resource_type ENUM('admin', 'profile') NOT NULL COMMENT '(DC2Type:resource_type)',
COMMENT '(DC2Type:resource_type)' :+1:  nice

2020-10-09 12:58 UTC, tiagopinheiro-kununu commented on services/src/Infrastructure/Persistence/Doctrine/Migrations/Version20201008163730.php
> +    changed_by VARCHAR(36) NOT NULL,
you can add a comment here maybe  COMMENT 'user_uuid)',

2020-10-09 13:35 UTC, davidribeiro-kununu commented on services/src/Infrastructure/Persistence/Doctrine/Migrations/Version20201008163730.php
> +    role_id INT UNSIGNED NOT NULL,
This is already in the createForeignKeyForUserRolesTable method

2020-10-09 13:48 UTC, davidribeiro-kununu commented on services/src/Infrastructure/Persistence/Doctrine/Type/ActionType.php
> +        return ['created', 'accepted', 'rejected', 'deleted'];
While it might make sense to create the constants, I think it's better to do it in another US, since this US's scope is just to create the database

2020-10-09 13:48 UTC, davidribeiro-kununu commented on services/src/Domain/Resource/ResourceType.php
> +    private const TYPES = ['admin', 'profile'];
While it might make sense to create the constants, I think it's better to do it in another US, since this US's scope is just to create the database

2020-10-09 13:50 UTC, davidribeiro-kununu commented on services/bin/run_startup.sh
> +if [ "${RESET_SCHEMA}" ]; then
add the APPLICATION_ENV condition to this check

2020-10-09 13:50 UTC, davidribeiro-kununu commented on services/composer.json
> +        "doctrine/orm": "^2.7",
done

2020-10-09 13:50 UTC, davidribeiro-kununu commented on services/src/Infrastructure/Persistence/Doctrine/Migrations/Version20201008163730.php
> +    changed_by VARCHAR(36) NOT NULL,
done

2020-10-09 13:51 UTC, davidribeiro-kununu commented
@tiagopinheiro-kununu can you take another look at this?

2020-10-09 15:31 UTC, tiagopinheiro-kununu reviewed
Looks good

2020-10-12 07:28 UTC, tiagopinheiro-kununu approved these changes
LGTM

2020-10-12 13:06 UTC, jcostaventureoak requested changes

2020-10-12 13:06 UTC, jcostaventureoak commented on services/bin/run_startup.sh
> +if [ "${APPLICATION_ENV}" == "dev" ]; then
The new k8s env uses the APPLICATION_ENV=development and not APPLICATION_ENV=dev. Probably we should take this also in consideration (or we add another validation or we change the roles service APPLICATION_ENV to development also in terraform env)

2020-10-12 13:26 UTC, davidribeiro-kununu commented on services/bin/run_startup.sh
> +if [ "${APPLICATION_ENV}" == "dev" ]; then
Maybe we should create a US to update all those APPLICATION_ENV=dev checks in this and others services.
I think that changing this now could be confusing, since we'd be having two checks (`APPLICATION_ENV=dev || APPLICATION_END=development`)

2020-10-12 20:37 UTC, kununu-drocha commented
just put some questions/doubts in the Confluence page https://confluence.xing.hh/pages/viewpage.action?pageId=386826843
Can you check please @davidribeiro-kununu ?
Sorry just was able to look at it now.

2020-10-13 08:32 UTC, davidribeiro-kununu commented
> just put some questions/doubts in the Confluence page https://confluence.xing.hh/pages/viewpage.action?pageId=386826843
> Can you check please @davidribeiro-kununu ?
> Sorry just was able to look at it now.

No problem, @kununu-drocha , already replied to your questions on confluence

2020-10-13 11:47 UTC, kununu-drocha commented
thanks @davidribeiro-kununu . Approach seems fine :wink:

2020-10-13 15:33 UTC, davidribeiro-kununu commented on services/src/Domain/Resource/ResourceType.php
> +            throw new \Exception();
this will done in a later US

2020-10-15 12:57 UTC, merged